//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataProcessingEntities : DbContext
    {
        public DataProcessingEntities()
            : base("name=DataProcessingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDataSet> ADDataSets { get; set; }
        public virtual DbSet<ADGeslacht> ADGeslachts { get; set; }
        public virtual DbSet<ADHerkomst> ADHerkomsts { get; set; }
        public virtual DbSet<ADPerioden> ADPeriodens { get; set; }
        public virtual DbSet<DSDataSet> DSDataSets { get; set; }
        public virtual DbSet<DSGeslacht> DSGeslachts { get; set; }
        public virtual DbSet<DSMboLeerwegEnNiveau> DSMboLeerwegEnNiveaux { get; set; }
        public virtual DbSet<DSMboRichtingEnSector> DSMboRichtingEnSectors { get; set; }
        public virtual DbSet<DSPerioden> DSPeriodens { get; set; }
        public virtual DbSet<DSPersoonsKenmerken> DSPersoonsKenmerkens { get; set; }
        public virtual DbSet<WBDataSet> WBDataSets { get; set; }
        public virtual DbSet<WBKenmerken> WBKenmerkens { get; set; }
        public virtual DbSet<WBPerioden> WBPeriodens { get; set; }
    }
}
