//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingDataImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDataSet
    {
        public int Id { get; set; }
        public string Geslacht { get; set; }
        public string Herkomst { get; set; }
        public string Perioden { get; set; }
        public Nullable<double> Alcoholgebruik { get; set; }
        public Nullable<double> BingeDrinken { get; set; }
        public Nullable<double> CannabisOoitGebruikt { get; set; }
        public Nullable<double> CannabisActiefGebruik { get; set; }
        public Nullable<double> TotaalGebruik { get; set; }
        public Nullable<double> XTC { get; set; }
        public Nullable<double> Cocaine { get; set; }
    }
}
