/*
Deployment script for DataProcessing

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "DataProcessing"
:setvar DefaultFilePrefix "DataProcessing"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)] COLLATE SQL_Latin1_General_CP1_CI_AS
GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY CHECKSUM,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 60 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF),
                MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = OFF,
                DELAYED_DURABILITY = DISABLED 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE = OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
    END


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating [dbo].[DSPersoonsKenmerken]...';


GO
CREATE TABLE [dbo].[DSPersoonsKenmerken] (
    [Key]         NVARCHAR (50)  NOT NULL,
    [Title]       NVARCHAR (50)  NULL,
    [Description] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[DSMboRichtingEnSector]...';


GO
CREATE TABLE [dbo].[DSMboRichtingEnSector] (
    [Key]         NVARCHAR (50)  NOT NULL,
    [Title]       NVARCHAR (50)  NULL,
    [Description] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[DSMboLeerwegEnNiveau]...';


GO
CREATE TABLE [dbo].[DSMboLeerwegEnNiveau] (
    [Key]         NVARCHAR (50)  NOT NULL,
    [Title]       NVARCHAR (50)  NULL,
    [Description] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[WBPerioden]...';


GO
CREATE TABLE [dbo].[WBPerioden] (
    [Key]    NVARCHAR (50)  NOT NULL,
    [Title]  NVARCHAR (50)  NULL,
    [Status] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[WBKenmerken]...';


GO
CREATE TABLE [dbo].[WBKenmerken] (
    [Key]         NVARCHAR (50)  NOT NULL,
    [Title]       NVARCHAR (50)  NULL,
    [Description] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[ADPerioden]...';


GO
CREATE TABLE [dbo].[ADPerioden] (
    [Key]    NVARCHAR (50)  NOT NULL,
    [Title]  NVARCHAR (50)  NULL,
    [Status] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[ADHerkomst]...';


GO
CREATE TABLE [dbo].[ADHerkomst] (
    [Key]             NVARCHAR (50) NOT NULL,
    [Title]           NVARCHAR (50) NULL,
    [CategoryGroupID] INT           NULL,
    CONSTRAINT [PK_ADHerkomst] PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[ADGeslacht]...';


GO
CREATE TABLE [dbo].[ADGeslacht] (
    [Key]   NVARCHAR (50) NOT NULL,
    [Title] NVARCHAR (50) NULL,
    CONSTRAINT [PK_ADGeslacht] PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[DSDataSet]...';


GO
CREATE TABLE [dbo].[DSDataSet] (
    [Id]                             INT           NOT NULL,
    [Geslacht]                       NVARCHAR (50) NULL,
    [MboLeerwegEnNiveau]             NVARCHAR (50) NULL,
    [MboRichtingEnSector]            NVARCHAR (50) NULL,
    [Persoonskenmerken]              NVARCHAR (50) NULL,
    [Perioden]                       NVARCHAR (50) NULL,
    [TotaalDoorstroomLeerling_1]     INT           NULL,
    [Leerjaar12_2]                   INT           NULL,
    [Vmbo3Totaal_3]                  INT           NULL,
    [Totaal_4]                       INT           NULL,
    [LandbouwBKG_5]                  INT           NULL,
    [ZorgEnWelzijnBKG_6]             INT           NULL,
    [EconomieBKG_7]                  INT           NULL,
    [TechniekBKG_8]                  INT           NULL,
    [CombinatieBKG_9]                INT           NULL,
    [GeenSectorT_10]                 INT           NULL,
    [Totaal_11]                      INT           NULL,
    [LandbouwBKG_12]                 INT           NULL,
    [ZorgEnWelzijnBKG_13]            INT           NULL,
    [EconomieBKG_14]                 INT           NULL,
    [TechniekBKG_15]                 INT           NULL,
    [CombinatieBKG_16]               INT           NULL,
    [GeenSectorT_17]                 INT           NULL,
    [Totaal_18]                      INT           NULL,
    [LandbouwBKG_19]                 INT           NULL,
    [ZorgEnWelzijnBKG_20]            INT           NULL,
    [EconomieBKG_21]                 INT           NULL,
    [TechniekBKG_22]                 INT           NULL,
    [CombinatieBKG_23]               INT           NULL,
    [GeenSectorT_24]                 INT           NULL,
    [Totaal_25]                      INT           NULL,
    [Totaal_26]                      INT           NULL,
    [BasisberoepsgerichteLeerweg_27] INT           NULL,
    [KaderberoepsgerichteLeerweg_28] INT           NULL,
    [Totaal_29]                      INT           NULL,
    [GemengdeLeerweg_30]             INT           NULL,
    [TheoretischeLeerweg_31]         INT           NULL,
    [Totaal_32]                      INT           NULL,
    [Totaal_33]                      INT           NULL,
    [BasisberoepsgerichteLeerweg_34] INT           NULL,
    [KaderberoepsgerichteLeerweg_35] INT           NULL,
    [Totaal_36]                      INT           NULL,
    [GemengdeLeerweg_37]             INT           NULL,
    [TheoretischeLeerweg_38]         INT           NULL,
    [Totaal_39]                      INT           NULL,
    [Landbouw_40]                    INT           NULL,
    [ZorgEnWelzijn_40]               INT           NULL,
    [Economie_42]                    INT           NULL,
    [Techniek_43]                    INT           NULL,
    [Combinatie_44]                  INT           NULL,
    [Totaal_45]                      INT           NULL,
    [Landbouw_46]                    INT           NULL,
    [ZorgEnWelzijn_47]               INT           NULL,
    [Economie_48]                    INT           NULL,
    [Techniek_49]                    INT           NULL,
    [Combinatie_50]                  INT           NULL,
    [Totaal_51]                      INT           NULL,
    [Landbouw_52]                    INT           NULL,
    [ZorgEnWelzijn_53]               INT           NULL,
    [Economie_54]                    INT           NULL,
    [Techniek_55]                    INT           NULL,
    [Combinatie_56]                  INT           NULL,
    [Totaal_57]                      INT           NULL,
    [Totaal_58]                      INT           NULL,
    [Landbouw_59]                    INT           NULL,
    [ZorgEnWelzijn_60]               INT           NULL,
    [Economie_61]                    INT           NULL,
    [Techniek_62]                    INT           NULL,
    [Combinatie_63]                  INT           NULL,
    [TheoretischeLeerweg_64]         INT           NULL,
    [HavoVwoInclAlgLeerjr_65]        INT           NULL,
    [Havo4Totaal_66]                 INT           NULL,
    [Havo5Totaal_67]                 INT           NULL,
    [Havo5MetDiploma_68]             INT           NULL,
    [Havo5ZonderDiploma_69]          INT           NULL,
    [Vwo46Totaal_70]                 INT           NULL,
    [Vwo6MetDiploma_71]              INT           NULL,
    [Vwo46ZonderDiploma_72]          INT           NULL,
    [Praktijkonderwijs_73]           INT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[WBDataSet]...';


GO
CREATE TABLE [dbo].[WBDataSet] (
    [Id]                                INT          NOT NULL,
    [Kenmerken]                         VARCHAR (50) NOT NULL,
    [Perioden]                          VARCHAR (50) NOT NULL,
    [WerkzameBeroepsbevolkingTotaal]    INT          NULL,
    [TotaalCreatieveBeroepen]           INT          NULL,
    [Kunsten]                           INT          NULL,
    [MediaEnEntertainment]              INT          NULL,
    [CreatieveZakelijkeDienstverlening] INT          NULL,
    [OverigeCreatieveBeroepen]          INT          NULL,
    [WerkzPersMetNietCreatieveBeroep]   INT          NULL,
    [WerkzPersMetBeroepOnbekend]        INT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ADDataSet]...';


GO
CREATE TABLE [dbo].[ADDataSet] (
    [Id]                    INT           NOT NULL,
    [Geslacht]              NVARCHAR (30) NOT NULL,
    [Herkomst]              NVARCHAR (30) NOT NULL,
    [Perioden]              NVARCHAR (30) NOT NULL,
    [Alcoholgebruik]        FLOAT (53)    NULL,
    [BingeDrinken]          FLOAT (53)    NULL,
    [CannabisOoitGebruikt]  FLOAT (53)    NULL,
    [CannabisActiefGebruik] FLOAT (53)    NULL,
    [TotaalGebruik]         FLOAT (53)    NULL,
    [XTC]                   FLOAT (53)    NULL,
    [Cocaine]               FLOAT (53)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[DSPerioden]...';


GO
CREATE TABLE [dbo].[DSPerioden] (
    [Key]         NVARCHAR (50)  NOT NULL,
    [Title]       NVARCHAR (50)  NULL,
    [Description] NVARCHAR (MAX) NULL,
    [Status]      NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
PRINT N'Creating [dbo].[DSGeslacht]...';


GO
CREATE TABLE [dbo].[DSGeslacht] (
    [Key]         NVARCHAR (50)  NOT NULL,
    [Title]       NVARCHAR (50)  NULL,
    [Description] NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET MULTI_USER 
    WITH ROLLBACK IMMEDIATE;


GO
PRINT N'Update complete.';


GO
