//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingDataImporter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataProcessingEntities : DbContext
    {
        public DataProcessingEntities()
            : base("name=DataProcessingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDataSet> ADDataSet { get; set; }
        public virtual DbSet<ADGeslacht> ADGeslacht { get; set; }
        public virtual DbSet<ADHerkomst> ADHerkomst { get; set; }
        public virtual DbSet<ADPerioden> ADPerioden { get; set; }
        public virtual DbSet<DSDataSet> DSDataSet { get; set; }
        public virtual DbSet<DSMboLeerwegEnNiveau> DSMboLeerwegEnNiveau { get; set; }
        public virtual DbSet<DSMboRichtingEnSector> DSMboRichtingEnSector { get; set; }
        public virtual DbSet<DSPersoonsKenmerken> DSPersoonsKenmerken { get; set; }
        public virtual DbSet<WBDataSet> WBDataSet { get; set; }
        public virtual DbSet<WBKenmerken> WBKenmerken { get; set; }
        public virtual DbSet<WBPerioden> WBPerioden { get; set; }
        public virtual DbSet<DSGeslacht> DSGeslacht { get; set; }
        public virtual DbSet<DSPerioden> DSPerioden { get; set; }
    }
}
