//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingDataImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSDataSet
    {
        public int Id { get; set; }
        public string Geslacht { get; set; }
        public string MboLeerwegEnNiveau { get; set; }
        public string MboRichtingEnSector { get; set; }
        public string Persoonskenmerken { get; set; }
        public string Perioden { get; set; }
        public Nullable<decimal> TotaalDoorstroomLeerling_1 { get; set; }
        public Nullable<decimal> Leerjaar12_2 { get; set; }
        public Nullable<decimal> Vmbo3Totaal_3 { get; set; }
        public Nullable<decimal> Totaal_4 { get; set; }
        public Nullable<decimal> LandbouwBKG_5 { get; set; }
        public Nullable<decimal> ZorgEnWelzijnBKG_6 { get; set; }
        public Nullable<decimal> EconomieBKG_7 { get; set; }
        public Nullable<decimal> TechniekBKG_8 { get; set; }
        public Nullable<decimal> CombinatieBKG_9 { get; set; }
        public Nullable<decimal> GeenSectorT_10 { get; set; }
        public Nullable<decimal> Totaal_11 { get; set; }
        public Nullable<decimal> LandbouwBKG_12 { get; set; }
        public Nullable<decimal> ZorgEnWelzijnBKG_13 { get; set; }
        public Nullable<decimal> EconomieBKG_14 { get; set; }
        public Nullable<decimal> TechniekBKG_15 { get; set; }
        public Nullable<decimal> CombinatieBKG_16 { get; set; }
        public Nullable<decimal> GeenSectorT_17 { get; set; }
        public Nullable<decimal> Totaal_18 { get; set; }
        public Nullable<decimal> LandbouwBKG_19 { get; set; }
        public Nullable<decimal> ZorgEnWelzijnBKG_20 { get; set; }
        public Nullable<decimal> EconomieBKG_21 { get; set; }
        public Nullable<decimal> TechniekBKG_22 { get; set; }
        public Nullable<decimal> CombinatieBKG_23 { get; set; }
        public Nullable<decimal> GeenSectorT_24 { get; set; }
        public Nullable<decimal> Totaal_25 { get; set; }
        public Nullable<decimal> Totaal_26 { get; set; }
        public Nullable<decimal> BasisberoepsgerichteLeerweg_27 { get; set; }
        public Nullable<decimal> KaderberoepsgerichteLeerweg_28 { get; set; }
        public Nullable<decimal> Totaal_29 { get; set; }
        public Nullable<decimal> GemengdeLeerweg_30 { get; set; }
        public Nullable<decimal> TheoretischeLeerweg_31 { get; set; }
        public Nullable<decimal> Totaal_32 { get; set; }
        public Nullable<decimal> Totaal_33 { get; set; }
        public Nullable<decimal> BasisberoepsgerichteLeerweg_34 { get; set; }
        public Nullable<decimal> KaderberoepsgerichteLeerweg_35 { get; set; }
        public Nullable<decimal> Totaal_36 { get; set; }
        public Nullable<decimal> GemengdeLeerweg_37 { get; set; }
        public Nullable<decimal> TheoretischeLeerweg_38 { get; set; }
        public Nullable<decimal> Totaal_39 { get; set; }
        public Nullable<decimal> Landbouw_40 { get; set; }
        public Nullable<decimal> ZorgEnWelzijn_40 { get; set; }
        public Nullable<decimal> Economie_42 { get; set; }
        public Nullable<decimal> Techniek_43 { get; set; }
        public Nullable<decimal> Combinatie_44 { get; set; }
        public Nullable<decimal> Totaal_45 { get; set; }
        public Nullable<decimal> Landbouw_46 { get; set; }
        public Nullable<decimal> ZorgEnWelzijn_47 { get; set; }
        public Nullable<decimal> Economie_48 { get; set; }
        public Nullable<decimal> Techniek_49 { get; set; }
        public Nullable<decimal> Combinatie_50 { get; set; }
        public Nullable<decimal> Totaal_51 { get; set; }
        public Nullable<decimal> Landbouw_52 { get; set; }
        public Nullable<decimal> ZorgEnWelzijn_53 { get; set; }
        public Nullable<decimal> Economie_54 { get; set; }
        public Nullable<decimal> Techniek_55 { get; set; }
        public Nullable<decimal> Combinatie_56 { get; set; }
        public Nullable<decimal> Totaal_57 { get; set; }
        public Nullable<decimal> Totaal_58 { get; set; }
        public Nullable<decimal> Landbouw_59 { get; set; }
        public Nullable<decimal> ZorgEnWelzijn_60 { get; set; }
        public Nullable<decimal> Economie_61 { get; set; }
        public Nullable<decimal> Techniek_62 { get; set; }
        public Nullable<decimal> Combinatie_63 { get; set; }
        public Nullable<decimal> TheoretischeLeerweg_64 { get; set; }
        public Nullable<decimal> HavoVwoInclAlgLeerjr_65 { get; set; }
        public Nullable<decimal> Havo4Totaal_66 { get; set; }
        public Nullable<decimal> Havo5Totaal_67 { get; set; }
        public Nullable<decimal> Havo5MetDiploma_68 { get; set; }
        public Nullable<decimal> Havo5ZonderDiploma_69 { get; set; }
        public Nullable<decimal> Vwo46Totaal_70 { get; set; }
        public Nullable<decimal> Vwo6MetDiploma_71 { get; set; }
        public Nullable<decimal> Vwo46ZonderDiploma_72 { get; set; }
        public Nullable<decimal> Praktijkonderwijs_73 { get; set; }
    }
}
