//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingDataImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSDataSet
    {
        public int Id { get; set; }
        public string Geslacht { get; set; }
        public string MboLeerwegEnNiveau { get; set; }
        public string MboRichtingEnSector { get; set; }
        public string Persoonskenmerken { get; set; }
        public string Perioden { get; set; }
        public Nullable<int> TotaalDoorstroomLeerling_1 { get; set; }
        public Nullable<int> Leerjaar12_2 { get; set; }
        public Nullable<int> Vmbo3Totaal_3 { get; set; }
        public Nullable<int> Totaal_4 { get; set; }
        public Nullable<int> LandbouwBKG_5 { get; set; }
        public Nullable<int> ZorgEnWelzijnBKG_6 { get; set; }
        public Nullable<int> EconomieBKG_7 { get; set; }
        public Nullable<int> TechniekBKG_8 { get; set; }
        public Nullable<int> CombinatieBKG_9 { get; set; }
        public Nullable<int> GeenSectorT_10 { get; set; }
        public Nullable<int> Totaal_11 { get; set; }
        public Nullable<int> LandbouwBKG_12 { get; set; }
        public Nullable<int> ZorgEnWelzijnBKG_13 { get; set; }
        public Nullable<int> EconomieBKG_14 { get; set; }
        public Nullable<int> TechniekBKG_15 { get; set; }
        public Nullable<int> CombinatieBKG_16 { get; set; }
        public Nullable<int> GeenSectorT_17 { get; set; }
        public Nullable<int> Totaal_18 { get; set; }
        public Nullable<int> LandbouwBKG_19 { get; set; }
        public Nullable<int> ZorgEnWelzijnBKG_20 { get; set; }
        public Nullable<int> EconomieBKG_21 { get; set; }
        public Nullable<int> TechniekBKG_22 { get; set; }
        public Nullable<int> CombinatieBKG_23 { get; set; }
        public Nullable<int> GeenSectorT_24 { get; set; }
        public Nullable<int> Totaal_25 { get; set; }
        public Nullable<int> Totaal_26 { get; set; }
        public Nullable<int> BasisberoepsgerichteLeerweg_27 { get; set; }
        public Nullable<int> KaderberoepsgerichteLeerweg_28 { get; set; }
        public Nullable<int> Totaal_29 { get; set; }
        public Nullable<int> GemengdeLeerweg_30 { get; set; }
        public Nullable<int> TheoretischeLeerweg_31 { get; set; }
        public Nullable<int> Totaal_32 { get; set; }
        public Nullable<int> Totaal_33 { get; set; }
        public Nullable<int> BasisberoepsgerichteLeerweg_34 { get; set; }
        public Nullable<int> KaderberoepsgerichteLeerweg_35 { get; set; }
        public Nullable<int> Totaal_36 { get; set; }
        public Nullable<int> GemengdeLeerweg_37 { get; set; }
        public Nullable<int> TheoretischeLeerweg_38 { get; set; }
        public Nullable<int> Totaal_39 { get; set; }
        public Nullable<int> Landbouw_40 { get; set; }
        public Nullable<int> ZorgEnWelzijn_40 { get; set; }
        public Nullable<int> Economie_42 { get; set; }
        public Nullable<int> Techniek_43 { get; set; }
        public Nullable<int> Combinatie_44 { get; set; }
        public Nullable<int> Totaal_45 { get; set; }
        public Nullable<int> Landbouw_46 { get; set; }
        public Nullable<int> ZorgEnWelzijn_47 { get; set; }
        public Nullable<int> Economie_48 { get; set; }
        public Nullable<int> Techniek_49 { get; set; }
        public Nullable<int> Combinatie_50 { get; set; }
        public Nullable<int> Totaal_51 { get; set; }
        public Nullable<int> Landbouw_52 { get; set; }
        public Nullable<int> ZorgEnWelzijn_53 { get; set; }
        public Nullable<int> Economie_54 { get; set; }
        public Nullable<int> Techniek_55 { get; set; }
        public Nullable<int> Combinatie_56 { get; set; }
        public Nullable<int> Totaal_57 { get; set; }
        public Nullable<int> Totaal_58 { get; set; }
        public Nullable<int> Landbouw_59 { get; set; }
        public Nullable<int> ZorgEnWelzijn_60 { get; set; }
        public Nullable<int> Economie_61 { get; set; }
        public Nullable<int> Techniek_62 { get; set; }
        public Nullable<int> Combinatie_63 { get; set; }
        public Nullable<int> TheoretischeLeerweg_64 { get; set; }
        public Nullable<int> HavoVwoInclAlgLeerjr_65 { get; set; }
        public Nullable<int> Havo4Totaal_66 { get; set; }
        public Nullable<int> Havo5Totaal_67 { get; set; }
        public Nullable<int> Havo5MetDiploma_68 { get; set; }
        public Nullable<int> Havo5ZonderDiploma_69 { get; set; }
        public Nullable<int> Vwo46Totaal_70 { get; set; }
        public Nullable<int> Vwo6MetDiploma_71 { get; set; }
        public Nullable<int> Vwo46ZonderDiploma_72 { get; set; }
        public Nullable<int> Praktijkonderwijs_73 { get; set; }
    }
}
