//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingDataImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSMboRichtingEnSector
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    }
}
