//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingDataImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBDataSet
    {
        public int Id { get; set; }
        public string Kenmerken { get; set; }
        public string Perioden { get; set; }
        public Nullable<decimal> WerkzameBeroepsbevolkingTotaal { get; set; }
        public Nullable<decimal> TotaalCreatieveBeroepen { get; set; }
        public Nullable<decimal> Kunsten { get; set; }
        public Nullable<decimal> MediaEnEntertainment { get; set; }
        public Nullable<decimal> CreatieveZakelijkeDienstverlening { get; set; }
        public Nullable<decimal> OverigeCreatieveBeroepen { get; set; }
        public Nullable<decimal> WerkzPersMetNietCreatieveBeroep { get; set; }
        public Nullable<decimal> WerkzPersMetBeroepOnbekend { get; set; }
    }
}
