//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessingDataImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class WBDataSet
    {
        public int Id { get; set; }
        public string Kenmerken { get; set; }
        public string Perioden { get; set; }
        public Nullable<int> WerkzameBeroepsbevolkingTotaal { get; set; }
        public Nullable<int> TotaalCreatieveBeroepen { get; set; }
        public Nullable<int> Kunsten { get; set; }
        public Nullable<int> MediaEnEntertainment { get; set; }
        public Nullable<int> CreatieveZakelijkeDienstverlening { get; set; }
        public Nullable<int> OverigeCreatieveBeroepen { get; set; }
        public Nullable<int> WerkzPersMetNietCreatieveBeroep { get; set; }
        public Nullable<int> WerkzPersMetBeroepOnbekend { get; set; }
    }
}
